global:
  checkNewVersion: false
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

api:
  dashboard: true
  insecure: true

log:
  level: DEBUG
  noColor: false
  maxSize: 50
  maxAge: 10
  maxBackups: 5
  compress: true

accessLog:
  addInternals: true
  bufferingSize: 100
  fields:
    names:
      StartUTC: drop
  filters:
    statusCodes:
      - "204-299"
      - "400-499"
      - "500-599"

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https

  https:
    address: ":443"
    http:
      tls:
        options: tls-opts@file
        certResolver: cloudflare
        domains:
          - main: local.mtopps.com
            sans:
              - "*.local.mtopps.com"

    forwardedHeaders:
      trustedIPs:
        - "192.168.1.0/24"
        - "172.20.0.0/16"
        - "10.0.0.0/8"

    transport:
      respondingTimeouts:
        readTimeout: 300s
        writeTimeout: 300s
        idleTimeout: 300s
      lifeCycle:
        requestAcceptGraceTimeout: 42s
        graceTimeOut: 42s

providers:
  providersThrottleDuration: 2s
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: media_net
  file:
    directory: /traefik_config
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: "info@mtopps.com"
      storage: /traefik_cert/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
        delayBeforeCheck: "90s"
