global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  # filePath: "/logs/logfile.log"
  level: DEBUG
  noColor: false
  maxSize:
  compress: true

accessLog:
  addInternals: true # things like ping@internal
  # filePath: /logs/traefik-access.log # In the Common Log Format (CLF) by default
  bufferingSize: 100 # Number of log lines
  fields:
    names:
      StartUTC: drop # Write logs in Container Local Time instead of UTC
  filters:
    statusCodes:
      - "204-299"
      - "400-499"
      - "500-599"

api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: local.mtopps.com
            sans:
              - "*.local.mtopps.com"
    forwardedHeaders:
      trustedIPs:
        - "192.168.1.0/24"
        - "172.20.0.0/16"
serversTransport:
  insecureSkipVerify: true
providers:
  providersThrottleDuration: 2s
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: media_net
  file:
    directory: /traefik_config
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: "info@mtopps.com"
      storage: /traefik_cert/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
