---
- name: Sync media server config
  hosts: all
  gather_facts: true
  vars_files:
    - vars/main.yml
    - vars/vault.yml

  tasks:
    - name: Copy directories to remote server
      ansible.builtin.copy:
        src: "files/home/matt/"
        dest: "{{ ansible_env.HOME }}"
        mode: "0775"

    - name: Create .env files from templates
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item | basename | regex_replace('\\.env\\.j2$', '') }}/.env"
        mode: "0775"
        backup: true
      loop: "{{ query('fileglob', 'templates/*.env.j2') }}"
      no_log: true

    - name: Start containers
      community.docker.docker_compose_v2:
        project_src: "{{ ansible_env.HOME }}/{{ item }}"
        state: present
        remove_orphans: true
        pull: never
      register: output
      loop:
        - homepage
        - media_server
        - traefik
        - dozzle
        - speedtest_tracker
