---
- name: Sync media server config
  hosts: all
  gather_facts: true

  tasks:
    - name: Create directories for docker compose configuration files
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        mode: '0755'
      loop: "{{ docker_compose_dirs }}"

    - name: Create .env files from templates
      ansible.builtin.template:
        src: "{{ item }}"
        dest: "{{ ansible_env.HOME }}/{{ item | basename | regex_replace('\\.env\\.j2$', '') }}/.env"
        mode: '0775'
        backup: true
      loop: "{{ query('fileglob', 'templates/*.env.j2') }}"
      no_log: true

    - name: Copy directories to remote server
      ansible.builtin.copy:
        src: "files/home/matt/{{ item }}/"
        dest: "{{ ansible_env.HOME }}/{{ item }}"
        mode: '0775'
      loop:
        - compose
        - homepage
        - media_server
        - containers

    - name: Create and start homepage container
      community.docker.docker_compose_v2:
        project_src: "{{ ansible_env.HOME }}/{{ item }}"
        state: present
        pull: always
      register: output
      loop:
        - homepage
        - media_server

    - name: Print output
      ansible.builtin.debug:
        var: output
