---
- Quick:
    - YouTube:
        - icon: youtube.svg
          href: https://youtube.com
          description: Videos
    - Proton Mail:
        - icon: proton-mail.svg
          href: https://mail.proton.me
          description: Encrypted Email
    - Reddit:
        - icon: reddit.svg
          href: https://reddit.com
          description: Reddit

- Access:
    - ChatGPT:
        - icon: chatgpt.svg
          href: https://chat.openai.com/
          description: Chat Bot
    - Google Gemini:
        - icon: google-gemini.svg
          href: https://gemini.google.com/
          description: Chat Bot 2
    - Logs:
        - icon: dozzle.svg
          href: {{HOMEPAGE_VAR_DOZZLE_URL}}
          description: Container Logs

- Torrent Sites:
    - BHD:
        - icon: https://beyond-hd.me/favicon.ico
          href: https://beyond-hd.me
          description: Beyond HD
    - iAnon:
        - icon: apple.svg
          href: https://ianon.app/
          description: macOS Apps
    - OPS:
        - icon: headphones.png
          href: https://orpheus.network/login.php
          description: Orpheus
