networks:
  media_net:
    external: true
    name: media_net

services:
  radarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: radarr
    hostname: radarr
    image: ghcr.io/hotio/radarr:latest
    volumes:
      - ${RADARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr-rtr.rule=Host(`radarr.local.mtopps.com`)
      - traefik.http.routers.radarr-rtr.entrypoints=https
      - traefik.http.routers.radarr-rtr.middlewares=chain-default@file
      - traefik.http.routers.radarr-rtr.service=radarr-svc
      - traefik.http.services.radarr-svc.loadbalancer.server.port=7878

  sonarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: sonarr
    hostname: sonarr
    image: ghcr.io/hotio/sonarr:latest
    volumes:
      - ${SONARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.local.mtopps.com`)
      - traefik.http.routers.sonarr-rtr.entrypoints=https
      - traefik.http.routers.sonarr-rtr.middlewares=chain-default@file
      - traefik.http.routers.sonarr-rtr.service=sonarr-svc
      - traefik.http.services.sonarr-svc.loadbalancer.server.port=8989

  prowlarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: prowlarr
    hostname: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    volumes:
      - ${PROWLARR_CONFIG_DIR}:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr-rtr.rule=Host(`prowlarr.local.mtopps.com`)
      - traefik.http.routers.prowlarr-rtr.entrypoints=https
      - traefik.http.routers.prowlarr-rtr.middlewares=chain-default@file
      - traefik.http.routers.prowlarr-rtr.service=prowlarr-svc
      - traefik.http.services.prowlarr-svc.loadbalancer.server.port=9696

  bazarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: bazarr
    hostname: bazarr
    image: ghcr.io/hotio/bazarr:latest
    volumes:
      - ${BAZARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr-rtr.rule=Host(`bazarr.local.mtopps.com`)
      - traefik.http.routers.bazarr-rtr.entrypoints=https
      - traefik.http.routers.bazarr-rtr.middlewares=chain-default@file
      - traefik.http.routers.bazarr-rtr.service=bazarr-svc
      - traefik.http.services.bazarr-svc.loadbalancer.server.port=6767
    environment:
      WEBUI_PORTS: 6767/tcp,6767/udp

  qbittorrent:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: qbittorrent
    hostname: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    ports:
      - 56097:56097
    volumes:
      - ${QBITTORRENT_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent-rtr.rule=Host(`qbittorrent.local.mtopps.com`)
      - traefik.http.routers.qbittorrent-rtr.entrypoints=https
      - traefik.http.routers.qbittorrent-rtr.middlewares=chain-default@file
      - traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc
      - traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8080
    environment:
      WEBUI_PORTS: 8080/tcp,8080/udp
      TORRENTING_PORT: 56097/tcp,56097/udp

  tautulli:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: tautulli
    hostname: tautulli
    image: ghcr.io/hotio/tautulli:latest
    volumes:
      - ${TAUTULLI_CONFIG_DIR}:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.local.mtopps.com`)
      - traefik.http.routers.tautulli-rtr.entrypoints=https
      - traefik.http.routers.tautulli-rtr.middlewares=chain-default@file
      - traefik.http.routers.tautulli-rtr.service=tautulli-svc
      - traefik.http.services.tautulli-svc.loadbalancer.server.port=8181

  jdownloader:
    extends:
      file: ../compose/base.yaml
      service: base
    container_name: jdownloader
    hostname: jdownloader
    image: jlesage/jdownloader-2:latest
    volumes:
      - ${JDOWNLOADER_CONFIG_DIR}:/config:rw
      - ${JDOWNLOADER_DATA_DIR}:/output:rw
    ports:
      - 5800:5800
    environment:
      USER_ID: ${DEFAULT_PUID}
      GROUP_ID: ${DEFAULT_PGID}
      DARK_MODE: 1
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      WEB_AUTHENTICATION: 1
      SECURE_CONNECTION: 1
