networks:
  media_net:
    external: true
    name: media_net

services:
  radarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: radarr
    hostname: radarr
    image: ghcr.io/hotio/radarr:latest
    volumes:
      - ${RADARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr-rtr.rule=Host(`radarr.local.mtopps.xyz`)
      - traefik.http.routers.radarr-rtr.entrypoints=https
      - traefik.http.routers.radarr-rtr.tls=true
      - traefik.http.services.radarr-svc.loadbalancer.server.port=7878

  sonarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: sonarr
    hostname: sonarr
    image: ghcr.io/hotio/sonarr:latest
    volumes:
      - ${SONARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr-rtr.rule=Host(`sonarr.local.mtopps.xyz`)
      - traefik.http.routers.sonarr-rtr.entrypoints=https
      - traefik.http.routers.sonarr-rtr.tls=true
      - traefik.http.services.sonarr-svc.loadbalancer.server.port=8989

  prowlarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: prowlarr
    hostname: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    volumes:
      - ${PROWLARR_CONFIG_DIR}:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr-rtr.rule=Host(`prowlarr.local.mtopps.xyz`)
      - traefik.http.routers.prowlarr-rtr.entrypoints=https
      - traefik.http.routers.prowlarr-rtr.tls=true
      - traefik.http.services.prowlarr-svc.loadbalancer.server.port=9696

  readarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: readarr
    hostname: readarr
    image: ghcr.io/hotio/readarr:latest
    volumes:
      - ${READARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.readarr-rtr.rule=Host(`readarr.local.mtopps.xyz`)
      - traefik.http.routers.readarr-rtr.entrypoints=https
      - traefik.http.routers.readarr-rtr.tls=true
      - traefik.http.services.readarr-svc.loadbalancer.server.port=8787

  lidarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: lidarr
    hostname: lidarr
    image: ghcr.io/hotio/lidarr:latest
    volumes:
      - ${LIDARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.lidarr-rtr.rule=Host(`lidarr.local.mtopps.xyz`)
      - traefik.http.routers.lidarr-rtr.entrypoints=https
      - traefik.http.routers.lidarr-rtr.tls=true
      - traefik.http.services.lidarr-svc.loadbalancer.server.port=8686

  bazarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: bazarr
    hostname: bazarr
    image: ghcr.io/hotio/bazarr:latest
    volumes:
      - ${BAZARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr-rtr.rule=Host(`bazarr.local.mtopps.xyz`)
      - traefik.http.routers.bazarr-rtr.entrypoints=https
      - traefik.http.routers.bazarr-rtr.tls=true
      - traefik.http.services.bazarr-svc.loadbalancer.server.port=6767
    environment:
      WEBUI_PORTS: 6767/tcp,6767/udp

  qbittorrent:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: qbittorrent
    hostname: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    ports:
      - 56097:56097
    volumes:
      - ${QBITTORRENT_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent-rtr.rule=Host(`qbittorrent.local.mtopps.xyz`)
      - traefik.http.routers.qbittorrent-rtr.entrypoints=https
      - traefik.http.routers.qbittorrent-rtr.tls=true
      - traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8080
    environment:
      WEBUI_PORTS: 8080/tcp,8080/udp
      TORRENTING_PORT: 56097/tcp,56097/udp

  tautulli:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: tautulli
    hostname: tautulli
    image: ghcr.io/hotio/tautulli:latest
    volumes:
      - ${TAUTULLI_CONFIG_DIR}:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.local.mtopps.xyz`)
      - traefik.http.routers.tautulli-rtr.entrypoints=https
      - traefik.http.routers.tautulli-rtr.tls=true
      - traefik.http.services.tautulli-svc.loadbalancer.server.port=8181

  jdownloader:
    extends:
      file: ../compose/base.yaml
      service: base
    container_name: jdownloader
    hostname: jdownloader
    image: jlesage/jdownloader-2:latest
    volumes:
      - ${JDOWNLOADER_CONFIG_DIR}:/config:rw
      - ${JDOWNLOADER_DATA_DIR}:/output:rw
    environment:
      USER_ID: ${DEFAULT_PUID}
      GROUP_ID: ${DEFAULT_PGID}
