networks:
  media_net:
    external: true
    name: media_net

services:
  radarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: radarr
    image: ghcr.io/hotio/radarr:latest
    volumes:
      - ${RADARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr-https.rule=Host(`radarr.local.mtopps.xyz`)
      - traefik.http.routers.radarr-https.entrypoints=websecure
      - traefik.http.routers.radarr-https.tls=true
      - traefik.http.routers.radarr-https.tls.certresolver=cloudflare
      - traefik.http.services.radarr-https.loadbalancer.server.port=7878

  sonarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: sonarr
    hostname: sonarr
    image: ghcr.io/hotio/sonarr:latest
    volumes:
      - ${SONARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr-https.rule=Host(`sonarr.local.mtopps.xyz`)
      - traefik.http.routers.sonarr-https.entrypoints=websecure
      - traefik.http.routers.sonarr-https.tls=true
      - traefik.http.routers.sonarr-https.tls.certresolver=cloudflare
      - traefik.http.services.sonarr-https.loadbalancer.server.port=8989

  prowlarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: prowlarr
    hostname: prowlarr
    image: ghcr.io/hotio/prowlarr:latest
    volumes:
      - ${PROWLARR_CONFIG_DIR}:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr-https.rule=Host(`prowlarr.local.mtopps.xyz`)
      - traefik.http.routers.prowlarr-https.entrypoints=websecure
      - traefik.http.routers.prowlarr-https.tls=true
      - traefik.http.routers.prowlarr-https.tls.certresolver=cloudflare
      - traefik.http.services.prowlarr-https.loadbalancer.server.port=9696

  readarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: readarr
    hostname: readarr
    image: ghcr.io/hotio/readarr:latest
    volumes:
      - ${READARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.readarr-https.rule=Host(`readarr.local.mtopps.xyz`)
      - traefik.http.routers.readarr-https.entrypoints=websecure
      - traefik.http.routers.readarr-https.tls=true
      - traefik.http.routers.readarr-https.tls.certresolver=cloudflare
      - traefik.http.services.readarr-https.loadbalancer.server.port=8787

  lidarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: lidarr
    hostname: lidarr
    image: ghcr.io/hotio/lidarr:latest
    volumes:
      - ${LIDARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.lidarr-https.rule=Host(`lidarr.local.mtopps.xyz`)
      - traefik.http.routers.lidarr-https.entrypoints=websecure
      - traefik.http.routers.lidarr-https.tls=true
      - traefik.http.routers.lidarr-https.tls.certresolver=cloudflare
      - traefik.http.services.lidarr-https.loadbalancer.server.port=8686

  bazarr:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: bazarr
    hostname: bazarr
    image: ghcr.io/hotio/bazarr:latest
    volumes:
      - ${BAZARR_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr-https.rule=Host(`bazarr.local.mtopps.xyz`)
      - traefik.http.routers.bazarr-https.entrypoints=websecure
      - traefik.http.routers.bazarr-https.tls=true
      - traefik.http.routers.bazarr-https.tls.certresolver=cloudflare
      - traefik.http.services.bazarr-https.loadbalancer.server.port=6767
    environment:
      WEBUI_PORTS: 6767/tcp,6767/udp

  qbittorrent:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: qbittorrent
    hostname: qbittorrent
    image: ghcr.io/hotio/qbittorrent:latest
    ports:
      - 56097:56097
    volumes:
      - ${QBITTORRENT_CONFIG_DIR}:/config
      - ${DEFAULT_DATA_DIR}:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.qbittorrent-https.rule=Host(`qbittorrent.local.mtopps.xyz`)
      - traefik.http.routers.qbittorrent-https.entrypoints=websecure
      - traefik.http.routers.qbittorrent-https.tls=true
      - traefik.http.routers.qbittorrent-https.tls.certresolver=cloudflare
      - traefik.http.services.qbittorrent-https.loadbalancer.server.port=8080
    environment:
      WEBUI_PORTS: 8080/tcp,8080/udp
      TORRENTING_PORT: 56097/tcp,56097/udp

  tautulli:
    extends:
      file: ../compose/arr.yaml
      service: arr-stack-container
    container_name: tautulli
    hostname: tautulli
    image: ghcr.io/hotio/tautulli:latest
    volumes:
      - ${TAUTULLI_CONFIG_DIR}:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli-https.rule=Host(`tautulli.local.mtopps.xyz`)
      - traefik.http.routers.tautulli-https.entrypoints=websecure
      - traefik.http.routers.tautulli-https.tls=true
      - traefik.http.routers.tautulli-https.tls.certresolver=cloudflare
      - traefik.http.services.tautulli-https.loadbalancer.server.port=8181

  jdownloader:
    extends:
      file: ../compose/base.yaml
      service: base
    container_name: jdownloader
    hostname: jdownloader
    image: jlesage/jdownloader-2:latest
    volumes:
      - ${JDOWNLOADER_CONFIG_DIR}:/config:rw
      - ${JDOWNLOADER_DATA_DIR}:/output:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.jdownloader-https.rule=Host(`jdownloader.local.mtopps.xyz`)
      - traefik.http.routers.jdownloader-https.entrypoints=websecure
      - traefik.http.routers.jdownloader-https.tls=true
      - traefik.http.routers.jdownloader-https.tls.certresolver=cloudflare
      - traefik.http.services.jdownloader-https.loadbalancer.server.port=5800
    environment:
      USER_ID: ${DEFAULT_PUID}
      GROUP_ID: ${DEFAULT_PGID}
