---
title: {{HOMEPAGE_VAR_TITLE}}

background: /images/lava-river.gif

cardBlur: md
backgroundOpacity: 0.6
headerStyle: underline
useEqualHeights: true
disableCollapse: true
hideVersion: false
showStats: true
statusStyle: "dot"
target: _blank

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  hideVisitURL: true

layout:
  Data:
    style: row
    columns: 1

  Downloads:
    style: row
    columns: 2

  Media:
    style: row
    columns: 4

  Infrastructure:
    style: row
    columns: 2

  Quick:
  Access:
  Torrent Sites:
    style: row
    columns: 2
