http:
  routers:
    synology-rtr:
      entryPoints:
        - "https"
      rule: "Host(`nas.local.mtopps.com`)"
      middlewares:
        - chain-secure
      tls: {}
      service: synology-svc

  services:
    synology-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.1.13:5001"
        passHostHeader: true
