---
networks:
  media_net:
    external: true

services:
  homepage:
    extends:
      file: ../compose/base.yaml
      service: base
    container_name: homepage
    hostname: homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: unless-stopped
    volumes:
      - ${HOMEPAGE_CONFIG_PATH}:/app/config
      - ${HOMEPAGE_DATA_ROOT_PATH}:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${HOMEPAGE_CONFIG_PATH}/images:/app/public/images
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage-rtr.rule=Host(`homepage.local.mtopps.com`)
      - traefik.http.routers.homepage-rtr.entrypoints=https
      - traefik.http.routers.homepage-rtr.tls=true
      - traefik.http.routers.homepage-rtr.service=homepage-svc
      - traefik.http.services.homepage-svc.loadbalancer.server.port=3000
    environment:
      HOMEPAGE_VAR_TITLE: ${HOMEPAGE_VAR_TITLE}
      HOMEPAGE_VAR_SEARCH_PROVIDER: ${HOMEPAGE_VAR_SEARCH_PROVIDER}
      HOMEPAGE_VAR_WEATHER_CITY: ${HOMEPAGE_VAR_WEATHER_CITY}
      HOMEPAGE_VAR_WEATHER_LAT: ${HOMEPAGE_VAR_WEATHER_LAT}
      HOMEPAGE_VAR_WEATHER_LONG: ${HOMEPAGE_VAR_WEATHER_LONG}
      HOMEPAGE_VAR_WEATHER_TZ: ${HOMEPAGE_VAR_WEATHER_TZ}
      HOMEPAGE_VAR_WEATHER_UNIT: ${HOMEPAGE_VAR_WEATHER_UNIT}
      HOMEPAGE_VAR_PROXMOX_URL: ${HOMEPAGE_VAR_PROXMOX_URL}
      HOMEPAGE_VAR_PROXMOX_USERNAME: ${HOMEPAGE_VAR_PROXMOX_USERNAME}
      HOMEPAGE_VAR_PROXMOX_PASSWORD: ${HOMEPAGE_VAR_PROXMOX_PASSWORD}
      HOMEPAGE_VAR_QBITTORRENT_URL: ${HOMEPAGE_VAR_QBITTORRENT_URL}
      HOMEPAGE_VAR_QBITTORRENT_USERNAME: ${HOMEPAGE_VAR_QBITTORRENT_USERNAME}
      HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ${HOMEPAGE_VAR_QBITTORRENT_PASSWORD}
      HOMEPAGE_VAR_RADARR_URL: ${HOMEPAGE_VAR_RADARR_URL}
      HOMEPAGE_VAR_RADARR_KEY: ${HOMEPAGE_VAR_RADARR_KEY}
      HOMEPAGE_VAR_SONARR_URL: ${HOMEPAGE_VAR_SONARR_URL}
      HOMEPAGE_VAR_SONARR_KEY: ${HOMEPAGE_VAR_SONARR_KEY}
      HOMEPAGE_VAR_PROWLARR_URL: ${HOMEPAGE_VAR_PROWLARR_URL}
      HOMEPAGE_VAR_PROWLARR_KEY: ${HOMEPAGE_VAR_PROWLARR_KEY}
      HOMEPAGE_VAR_BAZARR_URL: ${HOMEPAGE_VAR_BAZARR_URL}
      HOMEPAGE_VAR_BAZARR_KEY: ${HOMEPAGE_VAR_BAZARR_KEY}
      HOMEPAGE_VAR_PLEX_URL: ${HOMEPAGE_VAR_PLEX_URL}
      HOMEPAGE_VAR_PLEX_TOKEN: ${HOMEPAGE_VAR_PLEX_TOKEN}
      HOMEPAGE_VAR_TAUTULLI_URL: ${HOMEPAGE_VAR_TAUTULLI_URL}
      HOMEPAGE_VAR_TAUTULLI_KEY: ${HOMEPAGE_VAR_TAUTULLI_KEY}
      HOMEPAGE_VAR_DISKSTATION_URL: ${HOMEPAGE_VAR_DISKSTATION_URL}
      HOMEPAGE_VAR_DISKSTATION_USERNAME: ${HOMEPAGE_VAR_DISKSTATION_USERNAME}
      HOMEPAGE_VAR_DISKSTATION_PASSWORD: ${HOMEPAGE_VAR_DISKSTATION_PASSWORD}
      HOMEPAGE_VAR_TRAEFIK_URL: ${HOMEPAGE_VAR_TRAEFIK_URL}
      HOMEPAGE_VAR_TRAEFIK_USERNAME: ${HOMEPAGE_VAR_TRAEFIK_USERNAME}
      HOMEPAGE_VAR_TRAEFIK_PASSWORD: ${HOMEPAGE_VAR_TRAEFIK_PASSWORD}
      HOMEPAGE_VAR_SPEEDTEST_URL: ${HOMEPAGE_VAR_SPEEDTEST_URL}
